### ISSUE TITLE
[Nativescript-Vue] CSS file being loaded after home page is mounted

### ISSUE THREAD

**Issue by RosilBelli** [NathanWalker/nativescript-fonticon#29] opened 2019-11-12 01:08 UTC
For some unknown reason, I recently (NS 6.1+) started to face an issue that the FontIcon CSS file is being loaded after my app home page is mounted, therefore, no icon is shown. However, if I navigate to another page and go back to my home, all icons are now visible.

If on my home page loaded event I force a refresh through the key property on the outer gridlayout the icons appear, because they are already loaded.

Does anyone know how to solve this issue without forcing this layout refresh?

**Comment by logitron** [comment] 2019-11-27 13:47
I am also having this exact issue when I started upgrading all of my NPM packages.  I have isolated the problem to this specific upgrade:

`tns-core-modules: 6.0.1 -> 6.2.1`

It seems that the minor bump in this package introduced some change to cause this.

**Comment by logitron** [comment] 2019-11-27 17:25
Looks like with `tns-core-modules: 6.2+`, `TNSFontIcon.loadCss()` is resolving after the layout loads, whereas it was happening before the layout loads.

Digging into this library, I noticed that on `nativescript-fonticon.ts:29`, changing that logic to use `readTextSync()` vs `readText()` seems to resolve the issue.  I don't know if this would be the ultimate fix for this library.

I've also noticed that this library hasn't been active for a while, with several PR's looming.  I would put in a PR myself, but I have to ask: Is this library still being maintained?

**Comment by CarissaHurt** [comment] 2020-01-03 19:16
@logitron Hey, do you have example code for what you would do in the PR?

**Comment by logitron** [comment] 2020-01-03 19:52
@CarissaHurt : Something like this within the nativescript-fonticon.js:
```
var loadFile = function (path) {
  if (TNSFontIcon.debug) {
    console.log('----------');
    console.log("Loading collection '" + currentName + "' from file: " + path);
  }

  return new Promise(function (resolve, reject) {
    try {
      var cssFile = file_system_1.knownFolders.currentApp().getFile(path);
      var cssFileText = cssFile.readTextSync()
      var mapCss = lib.mapCss(cssFileText, TNSFontIcon.debug)
      TNSFontIcon.css[currentName] = mapCss;
      resolve()
    } catch (e) {
      reject(e)
    }
  })
};
```

I'm just not certain if this would be the ultimate fix.  It at least got me moving forward on my project.

**Comment by ronalson** [comment] 2020-01-17 19:15
Thanks, @logitron! 

Your solution works fine with `6.3.2`. I'll be using a fork with this implementation.

**Comment by Cyberkruz** [comment] 2020-02-12 00:03
@logitron Your fix worked for me as well. I noticed I only had the problem on Android in case someone is having a problem reproducing the issue.

**Comment by brysem** [comment] 2020-06-04 22:26
This appears to still be an issue in version 2.0.0 of nativescript-fonticon.
tns-core-modules 6.5.1

Any news or updates?

**Closed** 2020-07-15 01:25 UTC
